apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    nodePort: 30306 
  selector:
    app: mysql

